sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5-dev"
  - "pypy"
  - "pypy3"
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install twine
script: coverage run --source=utilis setup.py test
after_success: coveralls
deploy:
  provider: pypi
  user: joamag
  password:
    secure: m2HLHEjulyi13yVKVN7f//iuhTnMTmq1Bixdcqp7e0ndmNYXs5mqYXwPDo1dazQxTyVin8Go/IUYECJrVFDPCCzy8Dzi5fmuiPqmhwJ5YNuaAfd+xHJdawdWQAz3e2ZD16qamYRR+s04Rv7BySiD1UV8RpotQ0rYEuHXS4XoOgs=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
